export const exerciseData = {
  "Jambes": [
    { name: "Legs extension", videoUrl: "https://youtube.com/shorts/JPP4A_BcUx8?si=WF07l0cmDBulbzgu" },
    { name: "Legs curl assis", videoUrl: "https://youtube.com/shorts/aWbSqsBIXiU?si=XMXamzEnsrjJeeCU" },
    { name: "Legs curl allongé", videoUrl: "https://youtube.com/shorts/0jxpicak9mg?si=hojiWV3CwPp6wdgB" },
    { name: "Machine abduction", videoUrl: "https://youtube.com/shorts/GwfBFHRJkwQ?si=-zO-RGfjPgoRMs3j" },
    { name: "Machine adduction", videoUrl: "https://youtube.com/shorts/bNL8vUyRP68?si=8FJZbpa6yVorfWqn" },
    { name: "Press incliné", videoUrl: "https://youtube.com/shorts/ehUKQEM8nwA?si=CARPnhdwt8JtuR8y" },
    { name: "Press horizontal", videoUrl: "https://youtube.com/shorts/yNoPltAwIKI?si=I1MYfhYdZhXMGcBV" },
    { name: "Squat à la smith", videoUrl: "https://youtube.com/shorts/ess30psZKig?si=4kNZ1LREawBfrqv7" },
    { name: "Squat à la barre", videoUrl: "https://youtube.com/shorts/rwBxuJEri_s?si=XkOCNnxF0xoPrP02" },
    { name: "Fentes bulgares", videoUrl: "https://youtube.com/shorts/RM0pahubYp0?si=Uwnzin-LsbCtzWVe" },
    { name: "Goblet squat", videoUrl: "https://youtube.com/shorts/XCCtphV3da0?si=5kp5vvyqrTFmC5T2" },
    { name: "Nordic curl", videoUrl: "https://youtube.com/shorts/Csq1F5eBld0?si=ZoF4xCGThvaUWkhJ" },
    { name: "SDT jambes tendues", videoUrl: "https://youtube.com/shorts/GGILGAuOVrQ?si=2k7FDhHoSnP3IrxI" },
    { name: "Sysy squat à genoux", videoUrl: "https://youtube.com/shorts/3hQy2QBbrRk?si=vXYPKqYPoBBP2jYa" },
    { name: "Sysy squat debout", videoUrl: "https://youtube.com/shorts/HbUZ_4WhE78?si=C8_6XMqVmPFhqKJq" },
    { name: "Fentes box", videoUrl: "https://youtube.com/shorts/Fk0McdJV5Xw?si=2nwCETdo2bSzOtk1" },
    { name: "Hip thrust", videoUrl: "https://youtube.com/shorts/991jHWi06j0?si=5uNGiry8pthWhOoV" },
    { name: "Squat sauté", videoUrl: "https://youtube.com/shorts/A5z91UHxnmA" },
    { name: "Fentes alternées sautées", videoUrl: "https://youtube.com/shorts/azc7ZRJGtTg" },
    { name: "Squat en tension continue", videoUrl: "https://youtube.com/shorts/CMXfAKIEIxA" },
    { name: "Hip thrust machine", videoUrl: "https://youtube.com/shorts/1NWIS8IPNPw" },
    { name: "Hip thrust machine + step", videoUrl: "https://youtube.com/shorts/oUi6FuEq0E8" },
    { name: "Saut jambes tendues box", videoUrl: "https://youtube.com/shorts/-NOnaAjfGwQ" },
    { name: "Squat box", videoUrl: "https://youtube.com/shorts/kyfx_T4hx70" },
    { name: "SDT trap barre", videoUrl: "https://youtube.com/shorts/4JOlObArHws" },
    { name: "SDT jambe tendue unilatéral", videoUrl: "https://youtube.com/shorts/McFZFmBvEdQ" },
    { name: "Hack squat", videoUrl: "https://youtube.com/shorts/pv029A9qSaE" },
    { name: "Leg extensions + tapis", videoUrl: "https://youtube.com/shorts/Qk9fRpa6mVE" },
    { name: "Kick back", videoUrl: "https://youtube.com/shorts/NNHrPIJfxGs" },
    { name: "Kick back avec banc", videoUrl: "https://youtube.com/shorts/5P3U3b4Y4g8" }
  ],
  "Dos": [
    { name: "Tirage vertical neutre", videoUrl: "https://youtube.com/shorts/0SmUKTrJ1DY?si=fLbwTUY6lLyF3i65" },
    { name: "Tirage horizontal trapèze", videoUrl: "https://youtube.com/shorts/p21AWG9qipo?si=n0zRmttW5t3xf2F4" },
    { name: "Tirage vertical unilatéral", videoUrl: "https://youtube.com/shorts/0kxFZrBIhrc?si=Jze6ycxRoDljx3cS" },
    { name: "Tirage horizontal large", videoUrl: "https://youtube.com/shorts/CEUlSndewG4?si=Q1fJzab19Cb5sZP4" },
    { name: "Tirage horizontal neutre", videoUrl: "https://youtube.com/shorts/G2Wx7LI9Iuc?si=aoba2OuVqAw5kmr6" },
    { name: "Tirage horizontal unilatéral", videoUrl: "https://youtube.com/shorts/46ft5GCnSIU?si=xEhhB6Rq-_wOTCdS" },
    { name: "Élévation Y", videoUrl: "https://youtube.com/shorts/H6NSjWAGJ8c?si=Dp3RgHM6Qr3ouIBe" },
    { name: "Face pull", videoUrl: "https://youtube.com/shorts/NSfReJi-1Bs?si=NN0rQJ5xnAwDk_g_" },
    { name: "Traction", videoUrl: "https://youtube.com/shorts/mtKZxceRpXk?si=x1FI1a9_6DM7VTb5" },
    { name: "Traction excentrique", videoUrl: "https://youtube.com/shorts/y_WcGpfJ3fg?si=ljj1rxJBQ4r9tbt3" },
    { name: "Pull over", videoUrl: "https://youtube.com/shorts/BXd-nS37UvU?si=01SnbRgaJ1748zTV" },
    { name: "Gainage militaire", videoUrl: "https://youtube.com/shorts/YwqzLrH2Z5c" },
    { name: "Marche du fermier", videoUrl: "https://youtube.com/shorts/B4cd59dfgoY" },
    { name: "Tirage vertical supination", videoUrl: "https://youtube.com/shorts/FZ22sPG-sp0" },
    { name: "Tirage vertical pronation", videoUrl: "https://youtube.com/shorts/yfefL28jcLw" },
    { name: "Tirage vertical unilatéral avec banc", videoUrl: "https://youtube.com/shorts/rsjRuu36lAw" },
    { name: "Pull over unilatéral", videoUrl: "https://youtube.com/shorts/wwv7HTSWLFM" },
    { name: "Extension lombaire", videoUrl: "https://youtube.com/shorts/uRxQzqmdXoQ" },
    { name: "Rowing buste penché", videoUrl: "https://youtube.com/shorts/TSDAHeut2kI" },
    { name: "Rowing yet", videoUrl: "https://youtube.com/shorts/bq1BgqV6v7g" },
    { name: "Shrug barre hexagonale", videoUrl: "https://youtube.com/shorts/4zTVxiHJoQA" },
    { name: "Shrug barre hexagonale rapide", videoUrl: "https://youtube.com/shorts/M1xMV1lRt70" },
    { name: "Traction neutre", videoUrl: "https://youtube.com/shorts/pq4lnl3eIpA" },
    { name: "Traction supination", videoUrl: "https://youtube.com/shorts/jbJCYZv3mG8" },
    { name: "Tirage horizontal serré", videoUrl: "https://youtube.com/shorts/fQHJ87dSSgY" },
    { name: "Rack pool", videoUrl: "https://youtube.com/shorts/SAja2TLDbh4" },
    { name: "Tirage horizontal machine unilatérale", videoUrl: "https://youtube.com/shorts/M8WXeX_jsEk" }
  ],
  "Bras": [
    { name: "Machine à dips", videoUrl: "https://youtube.com/shorts/O2pqENNsEUU?si=Qzgdr9Lie8Kh53yk" },
    { name: "Extension triceps", videoUrl: "https://youtube.com/shorts/Sqpgd6OgDM0?si=XJadWKVSvjXXVqhy" },
    { name: "Barre au front", videoUrl: "https://youtube.com/shorts/LtIF-rMauSk?si=lhgS0gxo0l6M3yk0" },
    { name: "Barre au front PDC", videoUrl: "https://youtube.com/shorts/iiiiIYGvYgo?si=ynI0n9N1lhRwYU3H" },
    { name: "Curl pupitre", videoUrl: "https://youtube.com/shorts/WDP2K1qAPGA?si=2DFLLqrz0WtU_IaE" },
    { name: "Traction supination", videoUrl: "https://youtube.com/shorts/RpT-C_SJvCo?si=biTEWh7r1UmxyWy_" },
    { name: "Traction australienne", videoUrl: "https://youtube.com/shorts/E8hKYhrHq6Q?si=VgKc4ftA2ZjXT6tM" },
    { name: "Curl barre", videoUrl: "https://youtube.com/shorts/7_AjaZ0cvAg?si=Sc8CuksUKCnZtDgD" },
    { name: "Curl incliné", videoUrl: "https://youtube.com/shorts/72pqN5yfrw4?si=S1VFxazeivSmokEK" },
    { name: "Curl marteau", videoUrl: "https://youtube.com/shorts/8qc3CC6eeks?si=XTNuUcobcsOsDMwS" },
    { name: "Extension triceps poulie basse", videoUrl: "https://youtube.com/shorts/RpWhrgSvWmE" },
    { name: "Extension triceps poulie basse unilatérale", videoUrl: "https://youtube.com/shorts/Mm9J0fGRMjM" },
    { name: "Kick back triceps", videoUrl: "https://youtube.com/shorts/Dg9z1zZWwS0" },
    { name: "Extension triceps barre", videoUrl: "https://youtube.com/shorts/EizsrgOU2XM" },
    { name: "Extension triceps avec banc", videoUrl: "https://youtube.com/shorts/wT7ZSAF7D7w" },
    { name: "Barre au front extrême", videoUrl: "https://youtube.com/shorts/n75MT_HH4no" },
    { name: "Curl marteau assis", videoUrl: "https://youtube.com/shorts/mK3hLyrAUbg" },
    { name: "Curl assis", videoUrl: "https://youtube.com/shorts/0lYa8HB2JEI" },
    { name: "Curl marteau poulie basse", videoUrl: "https://youtube.com/shorts/jCwIYueURIw" },
    { name: "Curl poulie basse", videoUrl: "https://youtube.com/shorts/iSb0RzZBLEM" },
    { name: "Curl incliné poulies", videoUrl: "https://youtube.com/shorts/q877xBviJWQ" }
  ],
  "Pecs": [
    { name: "Machine convergente Bas des Pec", videoUrl: "https://youtube.com/shorts/VtZULb0bVKA?si=hZktXYWt2XN9lV7l" },
    { name: "Machine convergente haut des Pec", videoUrl: "https://youtube.com/shorts/TdQ3LumD1zw?si=bWaCa74TZVkY_TKh" },
    { name: "Machine unilatéral pec", videoUrl: "https://youtube.com/shorts/unqMuOHrOr4?si=JyX30210PlO8qPSQ" },
    { name: "Pec Deck", videoUrl: "https://youtube.com/shorts/E78GByPqNK0?si=LAXtrn9bVZyLwePY" },
    { name: "Incliné smith", videoUrl: "https://youtube.com/shorts/G6T-QW6_6ho?si=Y_ijDdKahO5EgsoL" },
    { name: "Dips", videoUrl: "https://youtube.com/shorts/xtNHtrLleFQ?si=syh9TIJI5vkuDFU0" },
    { name: "DC smith", videoUrl: "https://youtube.com/shorts/xKz468PskBw?si=fWD72fl7hCCsV93o" },
    { name: "DC machine", videoUrl: "https://youtube.com/shorts/X_Up2ASHl3E?si=YArLgx5kokeUgBHH" },
    { name: "Pompes", videoUrl: "https://youtube.com/shorts/RlgdqxKVg54?si=dzkRQuwO9x2HL0bz" },
    { name: "Haut de pecs poulie", videoUrl: "https://youtube.com/shorts/dwbq_ecrDao?si=feP0g7khhwMVf2Da" },
    { name: "DC haltère", videoUrl: "https://youtube.com/shorts/Jhsvgp9SGwM?si=k2IiOkXh8TX4fpDb" },
    { name: "DI haltère", videoUrl: "https://youtube.com/shorts/xJt7AWIwKTQ?si=IgvukDNJGtmVJAJ6" },
    { name: "DM barre", videoUrl: "https://youtube.com/shorts/HGX9Y95uxsM?si=gWUY-A9uGsjhWpOg" },
    { name: "Milieu de pec double poulies", videoUrl: "https://youtube.com/shorts/4-3SarQIQtc" },
    { name: "Bas de pec double poulies", videoUrl: "https://youtube.com/shorts/gy0E14JVBqc" },
    { name: "Haut de pec double poulies", videoUrl: "https://youtube.com/shorts/mFyT5JpwpI0" },
    { name: "Bas de pec poulie vis à vis", videoUrl: "https://youtube.com/shorts/nwrvs8rdgkU" },
    { name: "Milieu de pec poulie vis à vis", videoUrl: "https://youtube.com/shorts/rP73JQIUNOI" },
    { name: "Haut de pec poulie vis a vis", videoUrl: "https://youtube.com/shorts/5yU-ddcHLmw" },
    { name: "Milieu de pecs poulie vis à vis avec banc", videoUrl: "https://youtube.com/shorts/51DUMqw7hNw" },
    { name: "Bas de pecs poulie vis à vis avec banc", videoUrl: "https://youtube.com/shorts/4tON69wQ9e0" },
    { name: "Haut de pecs poulie vis à vis avec banc", videoUrl: "https://youtube.com/shorts/9eJj9PzpP04" },
    { name: "Pompes extrême", videoUrl: "https://youtube.com/shorts/CgEB4SlzyOA" },
    { name: "Écarté couché", videoUrl: "https://youtube.com/shorts/7HZ_sW2ROOs" },
    { name: "Pec deck extrême", videoUrl: "https://youtube.com/shorts/NMN1QScqcVE" }
  ],
  "Épaules": [
    { name: "DM", videoUrl: "https://youtube.com/shorts/XIzfIAlBEWE?si=DF7YH2hFM3VE_XFQ" },
    { name: "Pec deck a l’envers", videoUrl: "https://youtube.com/shorts/yNoPltAwIKI?si=I1MYfhYdZhXMGcBV" },
    { name: "Élévation latérale", videoUrl: "https://youtube.com/shorts/pErtAkDlTSE?si=sHjK0XsrmNVlCG_h" },
    { name: "DM haltère", videoUrl: "https://youtube.com/shorts/WkPotBiwW38?si=xcjYwZDC8kHQXH_N" },
    { name: "Tirage arrière d’épaule", videoUrl: "https://youtube.com/shorts/cXakzjagdwk?si=veQY1MH46Glj3OkK" },
    { name: "Élévation latérale poulie", videoUrl: "https://youtube.com/shorts/gS865di72kc?si=MuP-iT-hMeh7hlDg" },
    { name: "DM barre", videoUrl: "https://youtube.com/shorts/kD5Cf7cIC60?si=2arsMb6cykslkkGE" },
    { name: "Élévation frontale supination poulie", videoUrl: "https://youtube.com/shorts/1NbK6R753R4" },
    { name: "Élévation frontale corde", videoUrl: "https://youtube.com/shorts/thk_dLTVF8s" },
    { name: "Face pull arrière épaule", videoUrl: "https://youtube.com/shorts/N-N50GdjPlE" },
    { name: "Élévation latérale double poulie", videoUrl: "https://youtube.com/shorts/xUncdf0iocg" },
    { name: "Élévation latérale au sol", videoUrl: "https://youtube.com/shorts/KWGGJebRUJM" },
    { name: "Élévation latérale debout", videoUrl: "https://youtube.com/shorts/-hjVg7F0lvw" },
    { name: "Élévation latérale demi amplitude", videoUrl: "https://youtube.com/shorts/ve-3eYOsSOs" },
    { name: "Élévation frontale haltère", videoUrl: "https://youtube.com/shorts/xp1uakFSiGA" },
    { name: "Élévation frontale barre", videoUrl: "https://youtube.com/shorts/rYHch0Jqje8" },
    { name: "Élévation frontale complète", videoUrl: "https://youtube.com/shorts/Jhyixk6OcXE" },
    { name: "Oiseaux buste penché amélioré", videoUrl: "https://youtube.com/shorts/K6zgCBdzfY0" },
    { name: "Élévations latérales poulies vis à vis", videoUrl: "https://youtube.com/shorts/rMA2Fadk6zg" }
  ],
  "Abdos": [
    { name: "Gainage planche sur les mains", videoUrl: "https://youtube.com/shorts/agMDmU0hl0s" },
    { name: "Gainage planche", videoUrl: "https://youtube.com/shorts/0McUqSeLcik" },
    { name: "Gainage ballon sur les mains", videoUrl: "https://youtube.com/shorts/nYnoZQF_V4o" },
    { name: "Gainage ballon sur les coudes", videoUrl: "https://youtube.com/shorts/-ikS5088y28" },
    { name: "Gainage militaire", videoUrl: "https://youtube.com/shorts/YwqzLrH2Z5c" },
    { name: "Crunch au sol", videoUrl: "https://youtube.com/shorts/GqKnicXdjzw" },
    { name: "Mountain climber", videoUrl: "https://youtube.com/shorts/rVmbduor698" },
    { name: "Toes to bar", videoUrl: "https://youtube.com/shorts/6WvGMEQ2Szk" },
    { name: "Oblique T-bar", videoUrl: "https://youtube.com/shorts/ka35vdkKOSU" },
    { name: "Abdos sur banc + ballon", videoUrl: "https://youtube.com/shorts/Qp2V0NJ2XgM" },
    { name: "Crunch poulie", videoUrl: "https://youtube.com/shorts/EyZkA1kAXNQ" }
  ],
  "Exercice Atypique": [
    { name: "Mobilité au sol", videoUrl: "https://youtube.com/shorts/9gdDiToS5sc" },
    { name: "Burpees", videoUrl: "https://youtube.com/shorts/CdQdMBHi53E" },
    { name: "Escalier", videoUrl: "https://youtube.com/shorts/J9hfY9afLN8" },
    { name: "Rameur", videoUrl: "https://youtube.com/shorts/56eXH7_yEUk" },
    { name: "Suspension serviette", videoUrl: "https://youtube.com/shorts/CouT5fT87XQ" },
    { name: "Suspension barre", videoUrl: "https://youtube.com/shorts/TK9yNuuYrdQ" },
    { name: "Russian swing", videoUrl: "https://youtube.com/shorts/hwtjQhchdrM" },
    { name: "Burpees box", videoUrl: "https://youtube.com/shorts/GCJS7Vp8qwc" },
    { name: "Jet de balle allongé au sol", videoUrl: "https://youtube.com/shorts/n51J6ICEm4o" },
    { name: "Jet de balle en l’air", videoUrl: "https://youtube.com/shorts/mKQO4mtcUTQ" },
    { name: "Jet de balle au sol", videoUrl: "https://youtube.com/shorts/rpOK9vvzxew" }
  ]
};